# Nombre de la aplicación y Puerto
spring.application.name=ecopeques-backend
server.port=${PORT:8080}

# Configuración de Conexión a Base de Datos relacional
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecopeques_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Variables de Seguridad y Firma JWT
ecopeques.jwt.secret=${JWT_SECRET}
ecopeques.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}